apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pingdom-operator
spec:
  selector:
    matchLabels:
      name: pingdom-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: pingdom-operator
    spec:
      containers:
      - name: pingdom-operator
        image: quay.io/nalum/pingdom-operator
        imagePullPolicy: IfNotPresent
        args:
        - -pingdom-user=$PINGDOM_USER
        - -pingdom-password=$PINGDOM_PASSWORD
        env:
        - name: PINGDOM_USER
          valueFrom:
            secretKeyRef:
              name: pingdom-operator
              key: user-name
        - name: PINGDOM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pingdom-operator
              key: password
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
